use std::sync::Arc;

use jsonrpsee::{
    PendingSubscriptionSink,
    core::{RpcResult, SubscriptionResult},
    proc_macros::rpc,
};

use reth_ethereum::provider::db::{
    Database,
    transaction::{DbTx as _, DbTxMut as _},
};

use crate::db::{BlockEvent, EntityEvent, EntityKey, EntityTable, EntityValue, EventType};
use crate::rpc::notifier::EntityEventNotifier;

use super::{internal_error, spawn_event_subscription, try_send_event};

// Here `namespace = "reth"` means RPC methods will be prefixed with `reth_`, e.g.,
// `reth_get`, `reth_save`, `reth_subscribeEvents`, `reth_subscribeBlocks`

/// The #[rpc] macro generates RethEntityApiServer and RethEntityApiClient from RethEntityApi.
/// Check tests/* for RethEntityApiClient usage.
#[rpc(server, client, namespace = "reth")]
pub trait RethEntityApi {
    // Without #[method(name = "get"], it's just a regular trait method — not exposed via JSON-RPC.
    // The attribute is what tells jsonrpsee to register it as an RPC endpoint.
    // Also required by #[rpc], otherwise compile error
    /// Retrieves an entity value by key.
    #[method(name = "get")]
    fn get(&self, key: String) -> RpcResult<Option<String>>;

    /// Creates or updates an entity.
    #[method(name = "save")]
    fn save(&self, key: String, value: String) -> RpcResult<()>;

    /// Deletes an entity by key. Returns `true` if it existed.
    #[method(name = "delete")]
    fn delete(&self, key: String) -> RpcResult<bool>;

    /// Lets clients subscribe to real-time notifications when entities are
    /// saved/deleted. The [`EntityEventNotifier`] broadcasts events, and this subscription
    /// pushes them to any connected WebSocket subscriber.
    ///
    /// ```json
    /// // Client subscribes — the `id` is set by the client to match responses to requests:
    /// {"jsonrpc":"2.0","id": 1,"method":"reth_subscribeEvents","params":["my_key"]}
    ///
    /// // Server streams:
    /// {
    ///     "jsonrpc": "2.0",
    ///     "method": "reth_subscribeEvents",
    ///     "params": {
    ///         "subscription": 0,
    ///         "result": {
    ///             "event": "saved",
    ///             "key": "my_key",
    ///             "value": "new_value"
    ///         }
    ///     }
    /// }
    /// ```
    #[subscription(name = "subscribeEvents", item = EntityEvent, unsubscribe = "unsubscribeEvents")]
    fn subscribe_events(&self, key: Option<String>) -> SubscriptionResult;

    /// Subscribes to new block notifications via [`forward_block_events`].
    ///
    /// ```json
    /// // Client subscribes — the `id` is set by the client to match responses to requests:
    /// {"jsonrpc":"2.0","id": 1,"method":"reth_subscribeBlocks","params":[]}
    ///
    /// // Server streams:
    /// {
    ///     "jsonrpc": "2.0",
    ///     "method": "reth_subscribeBlocks",
    ///     "params": {
    ///         "subscription": 0,
    ///         "result": {
    ///             "block_number": 12345,
    ///             "block_hash": "0x...",
    ///             "parent_hash": "0x...",
    ///             "timestamp": 1234567890,
    ///             "tx_count": 42
    ///         }
    ///     }
    /// }
    /// ```
    #[subscription(name = "subscribeBlocks", item = BlockEvent, unsubscribe = "unsubscribeBlocks")]
    fn subscribe_blocks(&self) -> SubscriptionResult;
}

/// Backend for the `reth` namespace RPC, storing entities in MDBX.
pub struct RethEntityApiImpl {
    pub db: reth_ethereum::provider::db::DatabaseEnv,
    pub notifier: Arc<EntityEventNotifier>,
    pub block_event_sender: tokio::sync::broadcast::Sender<BlockEvent>,
}

impl RethEntityApiImpl {
    pub fn new(
        db: reth_ethereum::provider::db::DatabaseEnv,
        notifier: Arc<EntityEventNotifier>,
        block_event_sender: tokio::sync::broadcast::Sender<BlockEvent>,
    ) -> Self {
        Self {
            db,
            notifier,
            block_event_sender,
        }
    }
}

/// Server implementation of the [`RethEntityApi`] trait backed by MDBX.
// `RethEntityApiServer` Auto generated by #[rpc] attribute from RethEntityApi
impl RethEntityApiServer for RethEntityApiImpl {
    fn get(&self, key: String) -> RpcResult<Option<String>> {
        let tx = self.db.tx().map_err(|e| internal_error(e.to_string()))?;
        let result = tx
            .get::<EntityTable>(EntityKey(key.as_bytes().to_vec()))
            .map_err(|e| internal_error(e.to_string()))?;
        Ok(result.map(|v| String::from_utf8_lossy(&v.0).to_string()))
    }

    fn save(&self, key: String, value: String) -> RpcResult<()> {
        let tx = self
            .db
            .tx_mut()
            .map_err(|e| internal_error(e.to_string()))?;
        tx.put::<EntityTable>(
            EntityKey(key.as_bytes().to_vec()),
            EntityValue(value.as_bytes().to_vec()),
        )
        .map_err(|e| internal_error(e.to_string()))?;
        tx.commit().map_err(|e| internal_error(e.to_string()))?;
        self.notifier.notify(EntityEvent {
            event: EventType::Saved,
            key,
            value: Some(value),
        });
        Ok(())
    }

    fn delete(&self, key: String) -> RpcResult<bool> {
        let tx = self
            .db
            .tx_mut()
            .map_err(|e| internal_error(e.to_string()))?;
        let deleted = tx
            .delete::<EntityTable>(EntityKey(key.as_bytes().to_vec()), None)
            .map_err(|e| internal_error(e.to_string()))?;
        tx.commit().map_err(|e| internal_error(e.to_string()))?;
        if deleted {
            self.notifier.notify(EntityEvent {
                event: EventType::Deleted,
                key,
                value: None,
            });
        }
        Ok(deleted)
    }

    fn subscribe_events(
        &self,
        pending: PendingSubscriptionSink,
        key_filter: Option<String>,
    ) -> SubscriptionResult {
        let receiver = self.notifier.subscribe();
        spawn_event_subscription(pending, receiver, key_filter);
        Ok(())
    }

    fn subscribe_blocks(&self, pending: PendingSubscriptionSink) -> SubscriptionResult {
        let mut receiver = self.block_event_sender.subscribe();
        tokio::spawn(async move {
            let sink = match pending.accept().await {
                Ok(sink) => sink,
                Err(_) => return,
            };
            while let Ok(ref event) = receiver.recv().await {
                if !try_send_event(&sink, event).await {
                    break;
                }
            }
        });
        Ok(())
    }
}
