use std::sync::Arc;

use jsonrpsee::{
    PendingSubscriptionSink,
    core::{RpcResult, SubscriptionResult},
    proc_macros::rpc,
};

use crate::db::{EntityEvent, EventType, SqliteDb};
use crate::rpc::notifier::EntityEventNotifier;

use super::{internal_error, spawn_event_subscription};

/// Here `namespace = "sqlite"` means RPC methods will be prefixed with `sqlite_`, i.e.,
/// `sqlite_get`, `sqlite_save`, `sqlite_delete`, `sqlite_subscribeEvents`
///
/// The #[rpc] macro generates SqliteEntityApiServer and SqliteEntityApiClient from SqliteEntityApi.
/// Check tests/* for SqliteEntityApiClient usage.
#[rpc(server, client, namespace = "sqlite")]
pub trait SqliteEntityApi {
    /// Retrieves an entity value by key.
    #[method(name = "get")]
    fn get(&self, key: String) -> RpcResult<Option<String>>;

    /// Creates or updates an entity.
    #[method(name = "save")]
    fn save(&self, key: String, value: String) -> RpcResult<()>;

    /// Deletes an entity by key. Returns `true` if it existed.
    #[method(name = "delete")]
    fn delete(&self, key: String) -> RpcResult<bool>;

    /// Lets clients subscribe to real-time notifications when entities are
    /// saved/deleted. The `EntityEventNotifier` broadcasts events, and this subscription
    /// pushes them to any connected WebSocket subscriber.
    ///
    /// ```json
    /// {"jsonrpc": "2.0", "id": 1, "method": "sqlite_subscribeEvents", "params": ["my_key"]}
    ///
    /// {"jsonrpc": "2.0", "method": "sqlite_subscribeEvents", "params": {"subscription": 0, "result": {"event": "saved", "key": "my_key", "value": "new_value"}}}
    /// ```
    ///
    /// `params` can be empty to subscribe to all events:
    /// ```json
    /// {"jsonrpc": "2.0", "id": 1, "method": "sqlite_subscribeEvents", "params": []}
    /// ```
    /// That's the subscription ID assigned by the server — 0 is the first subscription.
    #[subscription(name = "subscribeEvents", item = EntityEvent, unsubscribe = "unsubscribeEvents")]
    fn subscribe_events(&self, key: Option<String>) -> SubscriptionResult;
}

/// Backend for the `sqlite` namespace RPC, storing entities in [`SqliteDb`].
pub struct SqliteEntityApiImpl {
    pub db: Arc<SqliteDb>,
    pub notifier: Arc<EntityEventNotifier>,
}

impl SqliteEntityApiImpl {
    pub fn new(db: Arc<SqliteDb>, notifier: Arc<EntityEventNotifier>) -> Self {
        Self { db, notifier }
    }
}

/// Server implementation of the [`SqliteEntityApiServer`] trait backed by [`SqliteDb`].
// `SqliteEntityApiServer` Auto-generated by #[rpc] attribute from SqliteEntityApi
impl SqliteEntityApiServer for SqliteEntityApiImpl {
    fn get(&self, key: String) -> RpcResult<Option<String>> {
        self.db.get(&key).map_err(|e| internal_error(e.to_string()))
    }

    fn save(&self, key: String, value: String) -> RpcResult<()> {
        self.db
            .save(&key, &value)
            .map_err(|e| internal_error(e.to_string()))?;
        self.notifier.notify(EntityEvent {
            event: EventType::Saved,
            key,
            value: Some(value),
        });
        Ok(())
    }

    fn delete(&self, key: String) -> RpcResult<bool> {
        let deleted = self
            .db
            .delete(&key)
            .map_err(|e| internal_error(e.to_string()))?;
        if deleted {
            self.notifier.notify(EntityEvent {
                event: EventType::Deleted,
                key,
                value: None,
            });
        }
        Ok(deleted)
    }

    // Check doc comments under `trait SqliteEntityApi::subscribe_events`
    fn subscribe_events(
        &self,
        pending: PendingSubscriptionSink,
        key_filter: Option<String>,
    ) -> SubscriptionResult {
        let receiver = self.notifier.subscribe();
        spawn_event_subscription(pending, receiver, key_filter);
        Ok(())
    }
}
